server:
  port: 9099

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: elastic-service
  elasticsearch:
    uris: http://localhost:9200

# JWT
myjwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}

myapplication:
  user-service:
    feign-client: http://localhost:9092/api/v1