server:
  port: 8889

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sezerlucianturkmen/Boost-Microservice-Fundamentals-config.git"
          default-label: main
          skip-ssl-validation: true
          username: sezerlucianturkmen
          password: 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
