apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-mongo
  labels:
    app: mongodbservice
spec:
  ports:
    - port: 27777
      targetPort: 27017
  selector:
    app: mongodb
  type: LoadBalancer