server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: bilgeadmin
    password: bilge!
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    username: 'postgres'
    password: 'root'
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/MicroAuthDB'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT
myjwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}